name: SonarQube CI Analysis
on:
  push:
    branches: [main, master, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=marvin00799_DVWA
            -Dsonar.organization=marvin00799
            -Dsonar.ci=true
            -Dsonar.projectBaseDir=${{ github.workspace }}
